<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BasketBaseTracker.Web\BasketBaseTracker.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>a74b88f0-690e-4458-882b-00831a94be64</UserSecretsId>
  </PropertyGroup>

</Project>
