<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\BasketBaseTracker.Web\BasketBaseTracker.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>77e1641c-446c-457c-92b0-37f11dee9654</UserSecretsId>
  </PropertyGroup>

</Project>
